### ISSUE TITLE
Document new areas: TUI mode and Record and reverse execution

### ISSUE THREAD

**Issue by marxin** [zxgio/gdb-cheatsheet#1]
I would like to thanks for a nice cheatsheet! I really like it.
Would you mind if I create a pull request for topics mentioned in subject?

**Comment by zxgio** [comment]
Thanks! I'd love to expand the areas covered by the cheatsheet (in particular, record and reverse execution seem extremely useful!). The only problem I see is that I tried very hard to keep the cheatsheet limited to one (double-sided) page. The sheet is currently pretty full and each time I add something I need to remove something else ... 
Maybe it's time to release the one-sheet constraint or, maybe, remove something and/or move some of the current contents into a different "getting started" document.
We'll see ... let's try :-)

**Comment by marxin** [comment]
In my opinion the sheet is quite dense and full. I would relax the rule of one double-sided page :)
I'll start with TUI and then we can discuss further arrangement of the sheet.

**Comment by zxgio** [comment]
Ok!
