### ISSUE TITLE
Can't compile with pdflatex

### ISSUE THREAD

**Issue by marxin** [zxgio/gdb-cheatsheet#2]
Using following pdflatex:
```
pdflatex --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/TeX Live for SUSE Linux)
```

I see errors in attached file.
[gdb-cheatsheet.log](https://github.com/zxgio/gdb-cheatsheet/files/1913052/gdb-cheatsheet.log)

**Comment by zxgio** [comment]
You didn't read the README, didn't you? ;-)
It's tex, not latex; use: pdftex gdb-cheatsheet.tex

**Comment by marxin** [comment]
Sorry, I did but read it in a wrong way :)
